version: '3.8'
services:
  nginx:
    image: nginx
    container_name: nginx 
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web:
    image: developer-portfolio
    container_name: developer-portfolio-web
    restart: always
    ports:
      - 8080:8080
    env_file: .env.local
    depends_on:
      - nginx