import styles from './globals.module.scss';
import '../scss/base/_reset.scss';

import ThemeRegistry from '@/theme/ThemeRegistry';
import { Container, Header } from '@/layout';

import type { Metadata } from 'next';


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/devicons/devicon@v2.15.1/devicon.min.css" />
      </head>

      <ThemeRegistry>
        <body className={styles.Body}>

          <Header />

          <main className={styles.Main}>
            <Container>
              {children}
            </Container>
          </main>

          {/* Footer */}

        </body>
      </ThemeRegistry>
    </html>
  );
}
